-- -------------------------------------------------------------
-- Database: subcategories
-- Generation Time: 2022-02-23 20:06:16.0170
-- -------------------------------------------------------------


DROP TABLE IF EXISTS "public"."subcategories";
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.

-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS subcategories_id_seq;

-- Table Definition
CREATE TABLE "public"."subcategories" (
    "id" int4 NOT NULL DEFAULT nextval('subcategories_id_seq'::regclass),
    "name" varchar(255) NOT NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "category_id" int4,
    CONSTRAINT "subcategories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

INSERT INTO "public"."subcategories" ("category_id", "name", "created_at", "updated_at") VALUES
(1, 'Ferme de animale', NOW(), NOW() ),
(1, 'Constructii si amenajari ferme', NOW(), NOW() ),
(1, 'Abatorizare', NOW(), NOW() ),
(1, 'Carmangerii si macelarii', NOW(), NOW() ),
(1, 'Servicii veterinare', NOW(), NOW() ),
(1, 'Laboratoare de analize', NOW(), NOW() ),
(1, 'Asociatii si federatii (Agricultura si alimente)', NOW(), NOW() ),
(1, 'Ferme vegetale', NOW(), NOW() ),
(1, 'Servicii agricole', NOW(), NOW() ),
(1, 'Inginer agronom', NOW(), NOW() ),
(1, 'Morarit', NOW(), NOW() ),
(1, 'Vinificatie', NOW(), NOW() ),
(1, 'Cultivare si procesare fructe si legume', NOW(), NOW() ),
(1, 'Prelucrare plante tehnice si medicinale', NOW(), NOW() ),
(1, 'Agricultura ecologica', NOW(), NOW() ),
(1, 'Utilaje agricole', NOW(), NOW() ),
(1, 'Alte servicii de agricultura', NOW(), NOW() ),
(1, 'Cultivare si procesare plante aromatice si medicinale', NOW(), NOW() ),
(1, 'Produse si alimente', NOW(), NOW() ),
(2, 'Montaj reclame', NOW(), NOW() ),
(2, 'Reparatii/renovari', NOW(), NOW() ),
(2, 'Siliconare/schimbare geamuri', NOW(), NOW() ),
(2, 'Jgeaburi/burlane', NOW(), NOW() ),
(2, 'Montaje antene si componente telecomunicatii', NOW(), NOW() ),
(2, 'Escalada blocuri', NOW(), NOW() ),
(2, 'Degajari zone cu risc', NOW(), NOW() ),
(2, 'Inspectii foto-video', NOW(), NOW() ),
(2, 'Iluminare ambientala', NOW(), NOW() ),
(2, 'Toaletari arbori', NOW(), NOW() ),
(2, 'Salvari animale', NOW(), NOW() ),
(2, 'Alte servicii de alpinism utilitar', NOW(), NOW() ),
(3, 'Asigurari auto', NOW(), NOW() ),
(3, 'Asigurari casco', NOW(), NOW() ),
(3, 'Asigurari ROTR', NOW(), NOW() ),
(3, 'Asigurari locuinte si cladiri', NOW(), NOW() ),
(3, 'Asigurari bunuri', NOW(), NOW() ),
(3, 'Asigurari marfa (CMR)', NOW(), NOW() ),
(3, 'Asigurari de viata', NOW(), NOW() ),
(3, 'Asigurari de vacante si calatorii', NOW(), NOW() ),
(3, 'Asigurari de sanatate', NOW(), NOW() ),
(3, 'Asigurari pentru sportivi', NOW(), NOW() ),
(3, 'Asigurari tehnice', NOW(), NOW() ),
(3, 'Asigurari pentru business', NOW(), NOW() ),
(3, 'Alte asigurari', NOW(), NOW() ),
(4, 'Firme si societati de consultanta juridica', NOW(), NOW() ),
(4, 'Avocati', NOW(), NOW() ),
(4, 'Notari', NOW(), NOW() ),
(4, 'Executori Judecatoresti', NOW(), NOW() ),
(4, 'Juristi', NOW(), NOW() ),
(4, 'Mediatori', NOW(), NOW() ),
(4, 'Alte servicii de asistenta si consultanta juridica', NOW(), NOW() ),
(5, 'Automobile', NOW(), NOW() ),
(5, 'Autoutilitare', NOW(), NOW() ),
(5, 'Camioane si autocare', NOW(), NOW() ),
(5, 'Motociclete si scutere', NOW(), NOW() ),
(5, 'Campere si rulote', NOW(), NOW() ),
(5, 'Remorci si platforme', NOW(), NOW() ),
(5, 'Biciclete', NOW(), NOW() ),
(5, 'Trotinete/vehicule electrice', NOW(), NOW() ),
(5, 'Barci', NOW(), NOW() ),
(5, 'Avioane usoare', NOW(), NOW() ),
(5, 'Vehicule agricole si industriale', NOW(), NOW() ),
(5, 'Alte vehicule', NOW(), NOW() ),
(6, 'Amenajari interioare', NOW(), NOW() ),
(6, 'Amenajari exterioare', NOW(), NOW() ),
(6, 'Zidarie si structuri', NOW(), NOW() ),
(6, 'Carotari', NOW(), NOW() ),
(6, 'Cosuri de fum si seminee', NOW(), NOW() ),
(6, 'Tamplarie, geamuri si usi', NOW(), NOW() ),
(6, 'Instalatii electrice', NOW(), NOW() ),
(6, 'Instalatii tehnico sanitare', NOW(), NOW() ),
(6, 'Utilitati, racordari, bransamente si resurse', NOW(), NOW() ),
(6, 'Instalatii de ventilatie si climatizare', NOW(), NOW() ),
(6, 'Acoperisuri', NOW(), NOW() ),
(6, 'Garduri, porti si usi de garaj', NOW(), NOW() ),
(6, 'Amenajari spatii verzi si spatii exterioare', NOW(), NOW() ),
(6, 'Mobila si decoratiuni', NOW(), NOW() ),
(6, 'Interfoane si sisteme de acces', NOW(), NOW() ),
(6, 'Lifturi, ascensoare si rampi', NOW(), NOW() ),
(6, 'Ignifugari', NOW(), NOW() ),
(6, 'Drumuri si poduri', NOW(), NOW() ),
(6, 'Pentru santier', NOW(), NOW() ),
(6, 'Materiale de constructii', NOW(), NOW() ),
(6, 'Avize, certificate si autorizatii', NOW(), NOW() ),
(6, 'Arhitectura si Design', NOW(), NOW() ),
(6, 'Topografie si Cadastru', NOW(), NOW() ),
(6, 'Proiectare', NOW(), NOW() ),
(6, 'Constructor de la A la Z', NOW(), NOW() ),
(6, 'Alte servicii de constructii', NOW(), NOW() ),
(6, 'Demolari', NOW(), NOW() ),
(7, 'Contabilitate primara', NOW(), NOW() ),
(7, 'Contabilitate de gestiune', NOW(), NOW() ),
(7, 'Contabilitate financiara', NOW(), NOW() ),
(7, 'Evidenta contabila', NOW(), NOW() ),
(7, 'Expertiza contabila', NOW(), NOW() ),
(7, 'Contabilitate manageriala', NOW(), NOW() ),
(7, 'Intocmire si certificare bilant', NOW(), NOW() ),
(7, 'Salarizare', NOW(), NOW() ),
(7, 'Audit', NOW(), NOW() ),
(7, 'Personal de ocazie (Contabilitate si audit)', NOW(), NOW() ),
(7, 'Programe si softuri pentru contabilitate', NOW(), NOW() ),
(7, 'Alte servicii de contabilitate si audit', NOW(), NOW() ),
(8, 'Consultanta si expertiza fiscala', NOW(), NOW() ),
(8, 'Controlling', NOW(), NOW() ),
(8, 'Analize financiare', NOW(), NOW() ),
(8, 'Consultanta financiara', NOW(), NOW() ),
(8, 'Consultanta in afaceri', NOW(), NOW() ),
(8, 'Cloud accounting', NOW(), NOW() ),
(8, 'Consultanta in atragerea fondurilor guvernamentale', NOW(), NOW() ),
(8, 'Consultanta in atragerea fondurilor europene', NOW(), NOW() ),
(8, 'Personal de ocazie (Consultanta si finantari)', NOW(), NOW() ),
(8, 'Alte servicii de consultanta si finantari', NOW(), NOW() ),
(8, 'Creditare', NOW(), NOW() ),
(8, 'Leasing auto', NOW(), NOW() ),
(8, 'Înfiintare firma', NOW(), NOW() ),
(9, 'Curatenie la domiciliu', NOW(), NOW() ),
(9, 'Curatenie dupa contructor', NOW(), NOW() ),
(9, 'Curatenie spatii verzi', NOW(), NOW() ),
(9, 'Intretinere spatii verzi', NOW(), NOW() ),
(9, 'Curatenie industriala', NOW(), NOW() ),
(9, 'Curatenie unitati sanitare', NOW(), NOW() ),
(9, 'Curatenie in spatii office si centre business', NOW(), NOW() ),
(9, 'Curatenie in centre comerciale', NOW(), NOW() ),
(9, 'Aparatura si produse igienico-sanitare', NOW(), NOW() ),
(9, 'Curatenie scari de bloc', NOW(), NOW() ),
(9, 'Echipamente pentru curatenie', NOW(), NOW() ),
(9, 'Colectare deseuri', NOW(), NOW() ),
(9, 'Vidanjare', NOW(), NOW() ),
(9, 'Spalatorii de haine si lenjerii', NOW(), NOW() ),
(9, 'Spalatorii de covoare', NOW(), NOW() ),
(9, 'Curatare si intretinere piscine', NOW(), NOW() ),
(9, 'Alte servicii de curatenie si menaj', NOW(), NOW() ),
(9, 'Curatare tapiterii', NOW(), NOW() ),
(10, 'Constructii si amenajari ferme', NOW(), NOW() ),
(10, 'Abatorizare', NOW(), NOW() ),
(10, 'Carmangerii si macelarii', NOW(), NOW() ),
(10, 'Servicii veterinare', NOW(), NOW() ),
(10, 'Laboratoare de analize', NOW(), NOW() ),
(10, 'Asociatii si federatii (Agricultura si alimente)', NOW(), NOW() ),
(10, 'Ferme vegetale', NOW(), NOW() ),
(10, 'Servicii agricole', NOW(), NOW() ),
(10, 'Inginer agronom', NOW(), NOW() ),
(10, 'Morarit', NOW(), NOW() ),
(10, '', NOW(), NOW() ),
(10, 'Cursuri aviatie si insotitori de bord', NOW(), NOW() ),
(10, 'Cursuri foto-video', NOW(), NOW() ),
(10, 'Cursuri beauty/infrumusetare', NOW(), NOW() ),
(10, 'Cursuri masaj', NOW(), NOW() ),
(10, 'Cursuri paza si protectie', NOW(), NOW() ),
(10, 'Cursuri militare', NOW(), NOW() ),
(10, 'Cursuri port-arma', NOW(), NOW() ),
(10, 'Cursuri dezvoltare personala', NOW(), NOW() ),
(10, 'Curs florar', NOW(), NOW() ),
(10, 'Curs formator', NOW(), NOW() ),
(10, 'Cursuri si meditatii limbi straine', NOW(), NOW() ),
(10, 'Cursuri si meditatii materii scolare', NOW(), NOW() ),
(10, 'Cursuri baby-sitter', NOW(), NOW() ),
(10, 'Cursuri medicale', NOW(), NOW() ),
(10, 'Cursuri reparatii auto', NOW(), NOW() ),
(10, 'Cursuri croitorie si design vestimentar', NOW(), NOW() ),
(10, 'Cursuri constructii', NOW(), NOW() ),
(10, 'Cursuri gastronomie', NOW(), NOW() ),
(10, 'Cursuri industria hoteliera', NOW(), NOW() ),
(10, 'Curs ghid turistic', NOW(), NOW() ),
(10, 'Cursuri IT si programare', NOW(), NOW() ),
(10, 'Cursuri marketing si vanzari', NOW(), NOW() ),
(10, 'Cursuri management', NOW(), NOW() ),
(10, 'Cursuri contabilitate', NOW(), NOW() ),
(10, 'Cursuri de dans', NOW(), NOW() ),
(10, 'Scoli de soferi si atestate pentru transport', NOW(), NOW() ),
(10, 'Protectia muncii', NOW(), NOW() ),
(10, 'Cursturi stivuitorist', NOW(), NOW() ),
(10, 'Cursuri modeling', NOW(), NOW() ),
(10, 'Cursuri agricultura', NOW(), NOW() ),
(10, 'Cursuri finantari si fonduri europene', NOW(), NOW() ),
(10, 'Cursuri de muzica', NOW(), NOW() ),
(10, 'Cursuri de actorie si teatru', NOW(), NOW() ),
(10, 'Arte plastice', NOW(), NOW() ),
(10, 'Alte cursuri', NOW(), NOW() ),
(10, 'Scoli si facultati private', NOW(), NOW() ),
(10, 'Cursuri conducator ambarcatiune', NOW(), NOW() ),
(11, 'Deratizare', NOW(), NOW() ),
(11, 'Dezinsectie', NOW(), NOW() ),
(11, 'Dezinfectie', NOW(), NOW() ),
(11, 'Decontaminari', NOW(), NOW() ),
(11, 'Decolmatari', NOW(), NOW() ),
(11, 'Alte servicii de deratizare si dezinfectie', NOW(), NOW() ),
(12, 'Pompe funebre', NOW(), NOW() ),
(12, 'Medic constatator', NOW(), NOW() ),
(12, 'Transport funerar', NOW(), NOW() ),
(12, 'Incinerare', NOW(), NOW() ),
(12, 'Accesorii pentru inmormantare', NOW(), NOW() ),
(12, 'Echipa pentru saparea gropii', NOW(), NOW() ),
(12, 'Imbalsamare si cosmetizare', NOW(), NOW() ),
(12, 'Organizarea ritualului religios', NOW(), NOW() ),
(12, 'Organizarea mesei de pomenire', NOW(), NOW() ),
(12, 'Monumente funerare', NOW(), NOW() ),
(12, 'Alte servicii funerare', NOW(), NOW() ),
(12, 'Servicii complete', NOW(), NOW() ),
(13, 'Website', NOW(), NOW() ),
(13, 'SEO', NOW(), NOW() ),
(13, 'Google Adwords', NOW(), NOW() ),
(13, 'Social Media Marketing', NOW(), NOW() ),
(13, 'Aplicatii mobile', NOW(), NOW() ),
(13, 'e-commerce', NOW(), NOW() ),
(13, 'Hosting / Gazduire web', NOW(), NOW() ),
(13, 'Design Grafic', NOW(), NOW() ),
(14, 'Vanzari', NOW(), NOW() ),
(14, 'Inchirieri', NOW(), NOW() ),
(14, 'Alte servicii imobiliare', NOW(), NOW() ),
(14, 'Evaluator proprietati imobiliare', NOW(), NOW() ),
(15, 'Aplicare gene', NOW(), NOW() ),
(15, 'Coafor', NOW(), NOW() ),
(15, 'Dermopigmentare', NOW(), NOW() ),
(15, 'Epilare definitiva', NOW(), NOW() ),
(15, 'Manichiura', NOW(), NOW() ),
(15, 'Pedichiura', NOW(), NOW() ),
(15, 'Intretinere si remodelare corporala', NOW(), NOW() ),
(15, 'Tratamente faciale', NOW(), NOW() ),
(15, 'Aparatura profesionala', NOW(), NOW() ),
(15, 'Produse profesionale', NOW(), NOW() ),
(15, 'Machiaj / Make-up', NOW(), NOW() ),
(15, 'Cosmetica', NOW(), NOW() ),
(15, 'Saloane de bronzat', NOW(), NOW() ),
(15, 'Frizerie / Barber-shop', NOW(), NOW() ),
(15, 'Tatuaje si piercing', NOW(), NOW() ),
(15, 'Unghii tehnice', NOW(), NOW() ),
(15, 'Alte servicii de infrumusetare', NOW(), NOW() ),
(15, 'Laminare gene - sprancene', NOW(), NOW() ),
(16, 'Centre Spa si Wellness', NOW(), NOW() ),
(16, 'Masaj', NOW(), NOW() ),
(16, 'Aparatura si mobilier masaj', NOW(), NOW() ),
(16, 'Centre de meditatii', NOW(), NOW() ),
(16, 'Alte servicii de relaxare', NOW(), NOW() ),
(17, 'Organizatori evenimente', NOW(), NOW() ),
(17, 'Sali de evenimente', NOW(), NOW() ),
(17, 'Dj', NOW(), NOW() ),
(17, 'Formatii si interpreti de muzica', NOW(), NOW() ),
(17, 'Lumini si fum', NOW(), NOW() ),
(17, 'Staroste', NOW(), NOW() ),
(17, 'Ursitoare', NOW(), NOW() ),
(17, 'Animatori pentru copii', NOW(), NOW() ),
(17, 'MC si prezentatori', NOW(), NOW() ),
(17, 'Foto', NOW(), NOW() ),
(17, 'Video', NOW(), NOW() ),
(17, 'Gheata carbonica', NOW(), NOW() ),
(17, 'Artificii', NOW(), NOW() ),
(17, 'Show-uri de comedie si divertisment', NOW(), NOW() ),
(17, 'Show-uri pentru adulti', NOW(), NOW() ),
(17, 'Hostess', NOW(), NOW() ),
(17, 'Modele', NOW(), NOW() ),
(17, 'Bar mobil', NOW(), NOW() ),
(17, 'Candy bar', NOW(), NOW() ),
(17, 'Decoratii si decoratiuni', NOW(), NOW() ),
(17, 'Inchirieri vesela si tacamuri', NOW(), NOW() ),
(17, 'Inchirieri si vanzari vestimentare', NOW(), NOW() ),
(17, 'Mijloace de transport pentru evenimente si ceremonii', NOW(), NOW() ),
(17, 'Personal de ocazie (Organizari evenimente)', NOW(), NOW() ),
(17, 'Catering', NOW(), NOW() ),
(17, 'Foodtruck si restaurante mobile', NOW(), NOW() ),
(17, 'Inchirieri sisteme de sonorizare', NOW(), NOW() ),
(17, 'Invitatii', NOW(), NOW() ),
(17, 'Marturii', NOW(), NOW() ),
(17, 'Toalete ecologice', NOW(), NOW() ),
(17, 'Alte servicii de organizari evenimente', NOW(), NOW() ),
(18, 'Baby-sitter', NOW(), NOW() ),
(18, 'Locuri si centre de joaca pentru copii', NOW(), NOW() ),
(18, 'Gradinite si crese private', NOW(), NOW() ),
(18, 'Cursuri pentru gravide', NOW(), NOW() ),
(18, 'Consultanti in alaptare', NOW(), NOW() ),
(18, 'Articole vestimentare si incaltaminte', NOW(), NOW() ),
(18, 'Jucarii', NOW(), NOW() ),
(18, 'Carucioare, mobilier si alte articole', NOW(), NOW() ),
(18, 'After-school', NOW(), NOW() ),
(18, 'Profesori de sprijin', NOW(), NOW() ),
(18, 'Terapie asistata de animale', NOW(), NOW() ),
(18, 'Alte servicii pentru copii', NOW(), NOW() ),
(19, 'Camine pentru batrani', NOW(), NOW() ),
(19, 'Centre de zi', NOW(), NOW() ),
(19, 'Cluburi de seniori', NOW(), NOW() ),
(19, 'Ingrijire la domiciliu', NOW(), NOW() ),
(19, 'Alte servicii pentru varstnici', NOW(), NOW() ),
(20, 'Cabinete veterinare', NOW(), NOW() ),
(20, 'Clinici veterinare', NOW(), NOW() ),
(20, 'Farmacii veterinare', NOW(), NOW() ),
(20, 'Asistenta medicala veterinare la domiciliu', NOW(), NOW() ),
(20, 'Toaletaj', NOW(), NOW() ),
(20, 'Toaletaj la domiciliu', NOW(), NOW() ),
(20, 'Pet shop-uri si magazine de accesorii', NOW(), NOW() ),
(20, 'Hoteluri si pensiuni pentru animale', NOW(), NOW() ),
(20, 'Dresaj', NOW(), NOW() ),
(20, 'Transport animale de companie', NOW(), NOW() ),
(20, 'Radiologie si imagistica veterinara', NOW(), NOW() ),
(20, 'Cimitir si crematoriu pentru animale', NOW(), NOW() ),
(20, 'Organizatori concursuri, targuri, expozitii', NOW(), NOW() ),
(20, 'Asociatii si federatii (Pet & vet)', NOW(), NOW() ),
(20, 'Handleri', NOW(), NOW() ),
(20, 'Pet-sitteri', NOW(), NOW() ),
(20, 'Urgente medicale veterinare', NOW(), NOW() ),
(20, 'Alte servicii pet & vet', NOW(), NOW() ),
(21, 'Automatizari industriale', NOW(), NOW() ),
(21, 'Birotica si papetarie', NOW(), NOW() ),
(21, 'Combustibil', NOW(), NOW() ),
(21, 'Industrie alimentara', NOW(), NOW() ),
(21, 'Confectii industriale', NOW(), NOW() ),
(21, 'Confectii metalice', NOW(), NOW() ),
(21, 'Prelucrari mecanice', NOW(), NOW() ),
(21, 'Prelucrari mecanice prin aschiere', NOW(), NOW() ),
(21, 'Taieri', NOW(), NOW() ),
(21, 'Indoiri, stantari', NOW(), NOW() ),
(21, 'Vopsitorii', NOW(), NOW() ),
(21, 'Galvanizare', NOW(), NOW() ),
(21, 'Zincare', NOW(), NOW() ),
(21, 'Cromare', NOW(), NOW() ),
(21, 'Nichelare', NOW(), NOW() ),
(21, 'Sablare', NOW(), NOW() ),
(21, 'Bobinaj', NOW(), NOW() ),
(21, 'Metalurgie', NOW(), NOW() ),
(21, 'Tipografii', NOW(), NOW() ),
(21, 'Bijuterii', NOW(), NOW() ),
(21, 'Gravuri', NOW(), NOW() ),
(21, 'Industria lemnului', NOW(), NOW() ),
(21, 'Alte servicii de productie si industrie', NOW(), NOW() ),
(21, 'Textile', NOW(), NOW() ),
(22, 'Agentii de publicitate', NOW(), NOW() ),
(22, 'Materiale publicitare', NOW(), NOW() ),
(22, 'Productie media', NOW(), NOW() ),
(22, 'Alte servicii de publicitate si promovare', NOW(), NOW() ),
(23, 'Reparatii calculatoare', NOW(), NOW() ),
(23, 'Reparatii telefoane mobile', NOW(), NOW() ),
(23, 'Reparatii acumulatori', NOW(), NOW() ),
(23, 'Reparatii bijuterii', NOW(), NOW() ),
(23, 'Reparatii ceasuri', NOW(), NOW() ),
(23, 'Reparatii scule mecanice', NOW(), NOW() ),
(23, 'Reparatii scule hidraulice si pneumatice', NOW(), NOW() ),
(23, 'Reparatii compresoare', NOW(), NOW() ),
(23, 'Reparatii motocositoare', NOW(), NOW() ),
(23, 'Reparatii drujbe', NOW(), NOW() ),
(23, 'Reparatii corpuri de iluminat', NOW(), NOW() ),
(23, 'Reparatii feronerie', NOW(), NOW() ),
(23, 'Croitorie', NOW(), NOW() ),
(23, 'Reparatii electrocasnice', NOW(), NOW() ),
(23, 'Reparatii imprimante si cartusuri', NOW(), NOW() ),
(23, 'Reparatii instrumente muzicale', NOW(), NOW() ),
(23, 'Reparatii lifturi civile', NOW(), NOW() ),
(23, 'Reparatii cantare electronice si mecanice', NOW(), NOW() ),
(23, 'Reparatii centrale electrice si sisteme de climatizare', NOW(), NOW() ),
(23, 'Reparatii centrale termice', NOW(), NOW() ),
(23, 'Reparatii si revizii sisteme de ignifugari', NOW(), NOW() ),
(23, 'Reparatii pantofarie si marochinarie', NOW(), NOW() ),
(23, 'Alte tipuri de reparatii', NOW(), NOW() ),
(24, 'Agentii de recrutare Romania', NOW(), NOW() ),
(24, 'Agentii de recrutare pentru strainatate', NOW(), NOW() ),
(24, 'Alte servicii de resurse umane', NOW(), NOW() ),
(25, 'Alarme si sisteme de securitate', NOW(), NOW() ),
(25, 'Garda de corp', NOW(), NOW() ),
(25, 'Paza evenimente', NOW(), NOW() ),
(25, 'Paza fixa (obiective fixe)', NOW(), NOW() ),
(25, 'Interventie rapida', NOW(), NOW() ),
(25, 'Proiectare sisteme de securitate', NOW(), NOW() ),
(25, 'Instalare sisteme de securitate', NOW(), NOW() ),
(25, 'Mentenanta sisteme de securitate', NOW(), NOW() ),
(25, 'Sisteme anti-incendiu', NOW(), NOW() ),
(25, 'Securitate informatica', NOW(), NOW() ),
(25, 'Detectivi particulari', NOW(), NOW() ),
(25, 'Transport valori', NOW(), NOW() ),
(25, 'Seifuri', NOW(), NOW() ),
(25, 'Alte servicii de securitate si paza', NOW(), NOW() ),
(26, 'Chirurgie', NOW(), NOW() ),
(26, 'Analize medicale', NOW(), NOW() ),
(26, 'Cardiologie', NOW(), NOW() ),
(26, 'Alergologie si imunologie', NOW(), NOW() ),
(26, 'Dermatologie si venerologie', NOW(), NOW() ),
(26, 'Diabet zaharat,nutritie si boli metabolice', NOW(), NOW() ),
(26, 'Endocrinologie', NOW(), NOW() ),
(26, 'Epidemiologie', NOW(), NOW() ),
(26, 'Gastroenterologie', NOW(), NOW() ),
(26, 'Genetica medicala', NOW(), NOW() ),
(26, 'Geriatrie si gerontologie', NOW(), NOW() ),
(26, 'Hematologie', NOW(), NOW() ),
(26, 'Medicina muncii', NOW(), NOW() ),
(26, 'Medicina de familie', NOW(), NOW() ),
(26, 'Medicina interna', NOW(), NOW() ),
(26, 'Medicina legala', NOW(), NOW() ),
(26, 'Medicina nucleara', NOW(), NOW() ),
(26, 'Medicina sportiva si recuperare medicala', NOW(), NOW() ),
(26, 'Urologie si nefrologie', NOW(), NOW() ),
(26, 'Neonatologie', NOW(), NOW() ),
(26, 'Neurologie', NOW(), NOW() ),
(26, 'Ortopedie si traumatologie', NOW(), NOW() ),
(26, 'ORL si audiometrie', NOW(), NOW() ),
(26, 'Pediatrie', NOW(), NOW() ),
(26, 'Pneumologie', NOW(), NOW() ),
(26, 'Psihiatrie', NOW(), NOW() ),
(26, 'Psihologie, psihoterapie si logopedie', NOW(), NOW() ),
(26, 'Reumatologie', NOW(), NOW() ),
(26, 'Stomatologie', NOW(), NOW() ),
(26, 'Oftalmologie si optica medicala', NOW(), NOW() ),
(26, 'Farmacii si produse farmaceutice', NOW(), NOW() ),
(26, 'Paliatie', NOW(), NOW() ),
(26, 'Celule stem', NOW(), NOW() ),
(26, 'Consumabile si aparatura medicala', NOW(), NOW() ),
(26, 'Dispozitive medicale ortopedice, proteze, orteze', NOW(), NOW() ),
(26, 'Ecografie, radiografie si imagistica medicala', NOW(), NOW() ),
(26, 'Ingrijire medicala la domiciliu', NOW(), NOW() ),
(26, 'Ambulante private', NOW(), NOW() ),
(26, 'Medicina alternativa', NOW(), NOW() ),
(26, 'Implant / Transplant par', NOW(), NOW() ),
(26, 'Alte servicii medicale', NOW(), NOW() ),
(26, 'Ginecologie si obstetrica', NOW(), NOW() ),
(27, 'Alte activitati indoor', NOW(), NOW() ),
(27, 'Personal trainer', NOW(), NOW() ),
(27, 'Articole sportive si echipamente', NOW(), NOW() ),
(27, 'Sali pentru fitness si bodybuilding', NOW(), NOW() ),
(27, 'Terenuri si spatii de sport (outdoor)', NOW(), NOW() ),
(27, 'Activitati in sali de sport (indoor)', NOW(), NOW() ),
(27, 'Circuite', NOW(), NOW() ),
(27, 'Jocuri de interior', NOW(), NOW() ),
(27, 'Alte activitati outdoor', NOW(), NOW() ),
(27, 'Pescuit', NOW(), NOW() ),
(27, 'Vanatoare', NOW(), NOW() ),
(27, 'Cursuri sportive', NOW(), NOW() ),
(28, 'Case de expeditii', NOW(), NOW() ),
(28, 'Dispecer/dispecerate', NOW(), NOW() ),
(28, 'Transport aerian', NOW(), NOW() ),
(28, 'Transport feroviar', NOW(), NOW() ),
(28, 'Transport naval', NOW(), NOW() ),
(28, 'Transport marfă', NOW(), NOW() ),
(28, 'Transport agabaritic', NOW(), NOW() ),
(28, 'Transport substante periculoase', NOW(), NOW() ),
(28, 'Transport persoane', NOW(), NOW() ),
(28, 'Distributie', NOW(), NOW() ),
(28, 'Curierat', NOW(), NOW() ),
(28, 'Tractari auto', NOW(), NOW() ),
(28, 'Transport auto', NOW(), NOW() ),
(28, 'Transport persoane ocazional', NOW(), NOW() ),
(28, 'Insotire - escortare transport agabaritic', NOW(), NOW() ),
(28, 'Carsharing', NOW(), NOW() ),
(28, 'Taximetrie', NOW(), NOW() ),
(28, 'Food delivery', NOW(), NOW() ),
(28, 'Curier dedicate', NOW(), NOW() ),
(28, 'Alte servicii de transport', NOW(), NOW() ),
(28, 'Transport nisip, piatra si moloz', NOW(), NOW() ),
(28, 'Mutări', NOW(), NOW() ),
(28, 'Transport frigorific', NOW(), NOW() ),
(28, 'Transport animale vii', NOW(), NOW() ),
(29, 'Cazare', NOW(), NOW() ),
(29, 'Drink & Party', NOW(), NOW() ),
(29, 'Food & Drink', NOW(), NOW() ),
(29, 'Domenii schiabile', NOW(), NOW() ),
(29, 'Muzee', NOW(), NOW() ),
(29, 'Gradini botanice', NOW(), NOW() ),
(29, 'Parcuri de distractii', NOW(), NOW() ),
(29, 'Parcuri de aventura', NOW(), NOW() ),
(29, 'Croaziere', NOW(), NOW() ),
(29, 'Drumetii', NOW(), NOW() ),
(29, 'Ghid turistic', NOW(), NOW() ),
(29, 'Aquapark si strand', NOW(), NOW() ),
(29, 'Alte locuri de interes', NOW(), NOW() ),
(29, 'Agenții de turism', NOW(), NOW() ),
(30, 'Comunicatii', NOW(), NOW() ),
(30, 'Deszapezire', NOW(), NOW() ),
(30, 'Depozitare', NOW(), NOW() ),
(30, 'Arhivare documente', NOW(), NOW() ),
(30, 'Automate de cafea si alte produse', NOW(), NOW() ),
(30, 'Traduceri', NOW(), NOW() ),
(30, 'Jocuri de noroc', NOW(), NOW() ),
(30, 'Callcenter', NOW(), NOW() ),
(30, 'Chei si deblocari', NOW(), NOW() ),
(30, 'Handmade', NOW(), NOW() ),
(30, 'Florarie si aranjamente florale', NOW(), NOW() ),
(30, 'Alte servicii diverse', NOW(), NOW() ),
(30, 'Tehnoredactare', NOW(), NOW() );
